# Site settings
name: MasterGossipBlog
email: daxuanguoshi@gmail.com
author: Gossip Wang
url: ''
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/WangGossip/
baseurl: ''
description: Actually, less is more!
meta_description: 
motto: It's our wits that make us men.
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 2a1f62e7cc45033e3da6cce061d75f12
revolvermaps: 5mozmyb225x
