# Site settings
name: MasterGossip's Blog
email: daxuanguoshi@gmail.com
author: Gossip Wang
url: https://wanggossip.github.io/
resume_site: https://wanggossip.github.io/
github: https://github.com/WangGossip/
baseurl: 
description: 做好喜欢的事情
meta_description: MasterGossip;个人博客;人要持之以恒
motto: 好好学习，天天向上
banner: 好好干！

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: WangGossip

# Build settings
markdown: kramdown
# 这两个要自己申请
baidu_analysis: 2a1f62e7cc45033e3da6cce061d75f12
revolvermaps: 5mozmyb225x
